version: '2'
services:

  php:
    build: ./php
    container_name: php7-fpm-alpine
    restart: always
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql
    container_name: mysql_php7-fpm-alpine
    restart: always
    volumes:
        - ./mysql/initdb/:/docker-entrypoint-initdb.d
        - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123132123
      - MYSQL_DATABASE=test_php7-fpm-alpine
      - MYSQL_USER=php7-fpm-alpine
      - MYSQL_PASSWORD=123456
  
  nginx:
    image: nginx:alpine
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 80:80

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "4000:80"